---
abstract: 'Haml plugin for Template Toolkit'
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Template: 0
  Template::Test: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Plugin-Haml
requires:
  Template::Plugin::Filter: 0
  Text::Haml: 0
  parent: 0
  perl: 5.006
resources:
  bugtracker: http://github.com/xenoterracide/Template-Plugin-Haml/issues
  repository: git://github.com/xenoterracide/Template-Plugin-Haml.git
version: 0.1.2
